server:
  port: 8089
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    address: 1.92.71.52:3306
    database: canal_manager
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: Root@123456
      jdbc-url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false

spring.datasource:
  address: 1.92.71.52:3306
  database: canal_manager
  username: root
  password: Root@123456
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://${spring.datasource.address}/${spring.datasource.database}?useUnicode=true&characterEncoding=UTF-8&useSSL=false
  hikari:
    maximum-pool-size: 30
    minimum-idle: 1

canal:
  adminUser: admin
  adminPasswd: admin
